- hosts: localhost
  vars:
     destdir: /prod/sec/
  tasks:
  - name: terraform Destroy 
    shell: |
      terraform init
      terraform fmt
      terraform validate
      terraform destroy
    args:
      chdir: "{{destdir}}/{{item.name}}{{item.id[0:7]}}"
    loop: "{{secdict}}"
    register: tfvalidate
    failed_when: "'Success' not in tfvalidate.stdout"
 
  

   
